### ISSUE TITLE
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)

### ISSUE THREAD

**Issue by peerschuett** [wagner-d/TimeSeAD#12]
Hi, I am trying to run your code and get some results for different models on the mini_smd dataset.

I executed `python test/test_experiment.py` and got the following error message:

```
Traceback (most recent call last):
  File "/localdata2/schu_p11/CASSy/TimeSeAD/test/test_experiment.py", line 74, in test
    self.assertEqual(run.returncode, 0, f'{experiment} failed to run!')
AssertionError: 1 != 0 : reconstruction.train_untrained_lstm_ae failed to run!

Stdout:
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/localdata2/schu_p11/CASSy/TimeSeAD/timesead_experiments/__init__.py", line 1, in <module>
    from . import utils
  File "/localdata2/schu_p11/CASSy/TimeSeAD/timesead_experiments/utils/__init__.py", line 1, in <module>
    from .dataset_ingredient import data_ingredient, load_dataset
  File "/localdata2/schu_p11/CASSy/TimeSeAD/timesead_experiments/utils/dataset_ingredient.py", line 12, in <module>
    data_ingredient = Ingredient('dataset')
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schu_p11/.conda/envs/timesead/lib/python3.11/site-packages/sacred/ingredient.py", line 75, in __init__
    ) = gather_sources_and_dependencies(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schu_p11/.conda/envs/timesead/lib/python3.11/site-packages/sacred/dependencies.py", line 728, in gather_sources_and_dependencies
    experiment_path, main = get_main_file(globs, save_git_info)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schu_p11/.conda/envs/timesead/lib/python3.11/site-packages/sacred/dependencies.py", line 599, in get_main_file
    main = Source.create(globs.get("__file__"), save_git_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schu_p11/.conda/envs/timesead/lib/python3.11/site-packages/sacred/dependencies.py", line 460, in create
    repo, commit, is_dirty = get_commit_if_possible(main_file, save_git_info)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schu_p11/.conda/envs/timesead/lib/python3.11/site-packages/sacred/dependencies.py", line 440, in get_commit_if_possible
    is_dirty = repo.is_dirty()
               ^^^^^^^^^^^^^^^
  File "/home/schu_p11/.conda/envs/timesead/lib/python3.11/site-packages/git/repo/base.py", line 949, in is_dirty
    if osp.isfile(self.index.path) and len(self.git.diff("--cached", *default_args)):
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schu_p11/.conda/envs/timesead/lib/python3.11/site-packages/git/cmd.py", line 986, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schu_p11/.conda/envs/timesead/lib/python3.11/site-packages/git/cmd.py", line 1598, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schu_p11/.conda/envs/timesead/lib/python3.11/site-packages/git/cmd.py", line 1388, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git diff --cached --abbrev=40 --full-index --raw
  stderr: 'error: unknown option `cached'
usage: git diff --no-index [<options>] <path> <path>
```

Is this caused by a faulty setup of the environment, or by something else? Thank you for your help :)

Best regards
Peer

**Comment by batman-nair** [comment]
Hi @peerschuett, this is the first time I've seen such an error so I'm not sure. Could you check your git version to make sure it supports the `--cached` flag? 
Assuming the git version is high enough, I did come across this [SO question](https://stackoverflow.com/questions/69470009/git-diff-cached-unknown-option-cached) which seems to share the same problem. 
Could you try running a git command like `git status` in the TimeSeAD repo directory to verify git is setup correctly?

**Comment by peerschuett** [comment]
Thank you for the fast feedback and your recommendation! The problem was caused by git. When I executed `git status`, I got a `fatal: detected dubious ownership in repository at /my/directory` error. I could resolve that by executing `git config --global --add safe.directory /my/directory`.

Now it works :)
